import { chromium } from "playwright";
const BASE = "http://127.0.0.1:3830";
const DIR = "C:/Users/scott/Desktop/Code/townreporter-dev/artifacts/gate-townreporter-2026-08-30/uiux-screens";
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, storageState: `${DIR}/_authstate.json` });
const page = await ctx.newPage();
await page.goto(BASE + "/desk/ops", { waitUntil: "load" });
await page.waitForTimeout(6000);
await page.screenshot({ path: `${DIR}/desk-ops-resolved-1440.png` });
console.log((await page.textContent("body")).slice(0, 2500));
await browser.close();
