; Definitions are generated by scripts/build-windows-setup.ps1, never on the user's PC.
#include "candidate.iss"

[Setup]
AppId=TownReporter
AppName=TownReporter
AppVersion={#AppVersion}
DefaultDirName={localappdata}\Programs\TownReporter
DisableDirPage=no
; One TownReporter per Windows user: an existing installation is upgraded in
; place, so the chosen folder defaults to the recorded one.
UsePreviousAppDir=yes
PrivilegesRequired=lowest
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
MinVersion=10.0
OutputDir={#OutputDir}
OutputBaseFilename=TownReporter-{#AppVersion}-Setup
Compression=lzma2
SolidCompression=yes
DiskSpanning=no
WizardStyle=modern
CloseApplications=no
RestartApplications=no
UninstallDisplayName=TownReporter {#AppVersion}

[Files]
Source: "{#StageDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{userprograms}\TownReporter\Start TownReporter"; Filename: "{app}\app\Start TownReporter.cmd"
Name: "{userprograms}\TownReporter\Stop TownReporter"; Filename: "{app}\app\Stop TownReporter.cmd"
Name: "{userprograms}\TownReporter\Restart TownReporter"; Filename: "{sys}\WindowsPowerShell\v1.0\powershell.exe"; Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\app\installer\Restart.ps1"""
Name: "{userprograms}\TownReporter\Health"; Filename: "{sys}\WindowsPowerShell\v1.0\powershell.exe"; Parameters: "-NoProfile -NoExit -ExecutionPolicy Bypass -File ""{app}\app\installer\Health.ps1"""
Name: "{userprograms}\TownReporter\Configure AI"; Filename: "{app}\app\Configure AI.cmd"

[Run]
Filename: "http://127.0.0.1:4388/desk"; Flags: shellexec postinstall skipifsilent; Description: "Open TownReporter"

[Code]
const
  { The uninstall key Inno writes for AppId=TownReporter. Inno appends _is1 to an
    AppId that is not a GUID, and PrivilegesRequired=lowest puts the key in the
    installing user's hive. Its "Inno Setup: App Path" value records the folder
    of the one installation this user already has. }
  UninstallKey = 'Software\Microsoft\Windows\CurrentVersion\Uninstall\TownReporter_is1';

var
  OwnerSetupMessage: String;

function InstalledAppPath(): String;
begin
  Result := '';
  RegQueryStringValue(HKCU, UninstallKey, 'Inno Setup: App Path', Result);
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  Entry: TFindRec;
  InstalledDir: String;
begin
  Result := '';
  InstalledDir := InstalledAppPath();
  if InstalledDir <> '' then begin
    { One TownReporter per Windows user. An existing installation is only ever
      upgraded in place: a second folder would replace its Add/Remove Programs
      entry and Start menu shortcuts while leaving the first copy orphaned. The
      private newsroom data lives outside the installation folder and is not
      touched by an upgrade. }
    if CompareText(RemoveBackslashUnlessRoot(ExpandConstant('{app}')), RemoveBackslashUnlessRoot(InstalledDir)) <> 0 then begin
      Result := 'TownReporter is already installed in:' + #13#10 +
        InstalledDir + #13#10 + #13#10 +
        'Only one copy can be installed, so Setup will not install a second one into a different folder.' + #13#10 +
        'Run Setup again and keep that folder to upgrade your newsroom, or uninstall TownReporter first.';
      Exit;
    end;
    Exit;
  end;
  if FileExists(ExpandConstant('{app}\app\.townreporter-install.json')) then
    Result := 'This folder already contains a TownReporter newsroom that Windows does not list as installed. This installer will not overwrite an unregistered copy. Uninstall the existing copy, then run Setup again. Nothing was changed.'
  else if FindFirst(ExpandConstant('{app}\*'), Entry) then begin
    try
      repeat
        if (Entry.Name <> '.') and (Entry.Name <> '..') then begin
          Result := 'Choose an empty installation folder. Existing files will not be overwritten.';
          Break;
        end;
      until not FindNext(Entry);
    finally
      FindClose(Entry);
    end;
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  Params, DataRoot, CodePath: String;
  SetupCode: AnsiString;
  ResultCode: Integer;
begin
  if CurStep = ssPostInstall then begin
    Params := '-NoProfile -NonInteractive -ExecutionPolicy Bypass -File "' + ExpandConstant('{app}\app\installer\FirstRun.ps1') + '" -NoBrowser';
    DataRoot := ExpandConstant('{param:DATAROOT|}');
    if DataRoot <> '' then Params := Params + ' -DataRoot "' + DataRoot + '"';
    if not Exec(ExpandConstant('{sys}\WindowsPowerShell\v1.0\powershell.exe'), Params,
      ExpandConstant('{app}\app'), SW_HIDE, ewWaitUntilTerminated, ResultCode) then
      RaiseException('Could not start offline initialization. Run app\Install TownReporter.cmd for diagnostics.');
    if ResultCode <> 0 then
      RaiseException('Offline initialization failed. Your data was preserved. Run app\Install TownReporter.cmd for diagnostics.');
    if LoadStringFromFile(ExpandConstant('{app}\app\.townreporter-setup-code-path.txt'), SetupCode) then begin
      CodePath := Trim(Utf8Decode(SetupCode));
      { FirstRun writes the path as UTF-8 without a BOM. The code stays in the protected data folder. }
      if LoadStringFromFile(CodePath, SetupCode) then
        OwnerSetupMessage := 'TownReporter is ready at http://127.0.0.1:4388.' + #13#10 + #13#10 +
          'Your first-owner setup code: ' + Trim(String(SetupCode)) + #13#10 +
          'Use this code when creating your editor account. It is also saved at:' + #13#10 + CodePath;
    end;
  end;
end;

procedure CurPageChanged(CurPageID: Integer);
begin
  if (CurPageID = wpFinished) and (OwnerSetupMessage <> '') then
    WizardForm.FinishedLabel.Caption := OwnerSetupMessage;
end;

function InitializeUninstall(): Boolean;
var
  ResultCode: Integer;
begin
  Result := True;
  if FileExists(ExpandConstant('{app}\app\.townreporter-install.json')) then begin
    Result := Exec(ExpandConstant('{sys}\WindowsPowerShell\v1.0\powershell.exe'),
      '-NoProfile -NonInteractive -ExecutionPolicy Bypass -File "' + ExpandConstant('{app}\app\installer\Stop.ps1') + '"',
      ExpandConstant('{app}\app'), SW_HIDE, ewWaitUntilTerminated, ResultCode);
    if Result then Result := ResultCode = 0;
    if not Result then MsgBox('Could not stop the owned newsroom. Run Stop TownReporter, then retry uninstall. Your data has been retained.', mbError, MB_OK);
  end;
end;
