; Definitions are generated by scripts/build-windows-setup.ps1, never on the user's PC.
#include "candidate.iss"

[Setup]
AppId=TownReporter
AppName=TownReporter
AppVersion={#AppVersion}
DefaultDirName={localappdata}\Programs\TownReporter
DisableDirPage=no
UsePreviousAppDir=no
PrivilegesRequired=lowest
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
MinVersion=10.0
OutputDir={#OutputDir}
OutputBaseFilename=TownReporter-{#AppVersion}-Setup
Compression=lzma2
SolidCompression=yes
DiskSpanning=no
WizardStyle=modern
CloseApplications=no
RestartApplications=no
UninstallDisplayName=TownReporter {#AppVersion}

[Files]
Source: "{#StageDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{userprograms}\TownReporter\Start TownReporter"; Filename: "{app}\app\Start TownReporter.cmd"
Name: "{userprograms}\TownReporter\Stop TownReporter"; Filename: "{app}\app\Stop TownReporter.cmd"
Name: "{userprograms}\TownReporter\Restart TownReporter"; Filename: "{sys}\WindowsPowerShell\v1.0\powershell.exe"; Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\app\installer\Restart.ps1"""
Name: "{userprograms}\TownReporter\Health"; Filename: "{sys}\WindowsPowerShell\v1.0\powershell.exe"; Parameters: "-NoProfile -NoExit -ExecutionPolicy Bypass -File ""{app}\app\installer\Health.ps1"""
Name: "{userprograms}\TownReporter\Configure AI"; Filename: "{app}\app\Configure AI.cmd"

[Run]
Filename: "http://127.0.0.1:4388/desk"; Flags: shellexec postinstall skipifsilent; Description: "Open TownReporter"

[Code]
var
  OwnerSetupMessage: String;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  Entry: TFindRec;
begin
  Result := '';
  if FileExists(ExpandConstant('{app}\app\.townreporter-install.json')) then
    Result := 'This folder already contains a configured newsroom. Stop it and preserve its data. Choose a separate empty folder; this installer does not upgrade an existing newsroom.'
  else if FindFirst(ExpandConstant('{app}\*'), Entry) then begin
    try
      repeat
        if (Entry.Name <> '.') and (Entry.Name <> '..') then begin
          Result := 'Choose an empty installation folder. Existing files will not be overwritten.';
          Break;
        end;
      until not FindNext(Entry);
    finally
      FindClose(Entry);
    end;
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  Params, DataRoot, CodePath: String;
  SetupCode: AnsiString;
  ResultCode: Integer;
begin
  if CurStep = ssPostInstall then begin
    Params := '-NoProfile -NonInteractive -ExecutionPolicy Bypass -File "' + ExpandConstant('{app}\app\installer\FirstRun.ps1') + '" -NoBrowser';
    DataRoot := ExpandConstant('{param:DATAROOT|}');
    if DataRoot <> '' then Params := Params + ' -DataRoot "' + DataRoot + '"';
    if not Exec(ExpandConstant('{sys}\WindowsPowerShell\v1.0\powershell.exe'), Params,
      ExpandConstant('{app}\app'), SW_HIDE, ewWaitUntilTerminated, ResultCode) then
      RaiseException('Could not start offline initialization. Run app\Install TownReporter.cmd for diagnostics.');
    if ResultCode <> 0 then
      RaiseException('Offline initialization failed. Your data was preserved. Run app\Install TownReporter.cmd for diagnostics.');
    if LoadStringFromFile(ExpandConstant('{app}\app\.townreporter-setup-code-path.txt'), SetupCode) then begin
      CodePath := Trim(Utf8Decode(SetupCode));
      { FirstRun writes the path as UTF-8 without a BOM. The code stays in the protected data folder. }
      if LoadStringFromFile(CodePath, SetupCode) then
        OwnerSetupMessage := 'TownReporter is ready at http://127.0.0.1:4388.' + #13#10 + #13#10 +
          'Your first-owner setup code: ' + Trim(String(SetupCode)) + #13#10 +
          'Use this code when creating your editor account. It is also saved at:' + #13#10 + CodePath;
    end;
  end;
end;

procedure CurPageChanged(CurPageID: Integer);
begin
  if (CurPageID = wpFinished) and (OwnerSetupMessage <> '') then
    WizardForm.FinishedLabel.Caption := OwnerSetupMessage;
end;

function InitializeUninstall(): Boolean;
var
  ResultCode: Integer;
begin
  Result := True;
  if FileExists(ExpandConstant('{app}\app\.townreporter-install.json')) then begin
    Result := Exec(ExpandConstant('{sys}\WindowsPowerShell\v1.0\powershell.exe'),
      '-NoProfile -NonInteractive -ExecutionPolicy Bypass -File "' + ExpandConstant('{app}\app\installer\Stop.ps1') + '"',
      ExpandConstant('{app}\app'), SW_HIDE, ewWaitUntilTerminated, ResultCode);
    if Result then Result := ResultCode = 0;
    if not Result then MsgBox('Could not stop the owned newsroom. Run Stop TownReporter, then retry uninstall. Your data has been retained.', mbError, MB_OK);
  end;
end;
