/**
 * Download the paper's webfonts and write a local @font-face sheet.
 *
 * The pages linked `fonts.googleapis.com` directly, so every reader's browser
 * announced itself to Google before a single word rendered. Self-hosting
 * removes that third-party dependency at build and runtime, and keeps the
 * paper working offline once the fonts are fetched once.
 *
 * Run this only when the font list changes; the files it writes are committed.
 * It is not part of the build: a build that reaches out to a third party to
 * succeed is exactly the dependency being removed.
 *
 *   node scripts/fetch-fonts.mjs
 *
 * Keeps the latin and latin-ext subsets. Longmont is not served by the Greek,
 * Cyrillic or Vietnamese cuts, and each one is another file to ship.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const GOOGLE_CSS =
  "https://fonts.googleapis.com/css2" +
  "?family=Fraunces:opsz,wght@9..144,500;9..144,600;9..144,700" +
  "&family=Source+Serif+4:ital,wght@0,400;0,600;1,400;1,600" +
  "&display=swap";

// Google serves woff2 only to a browser-shaped request; anything else gets the
// far larger legacy formats.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36";

const KEEP_SUBSETS = new Set(["latin", "latin-ext"]);

const root = process.cwd();
const outDir = join(root, "public", "fonts");
await mkdir(outDir, { recursive: true });

const css = await (await fetch(GOOGLE_CSS, { headers: { "User-Agent": UA } })).text();

/** Each block is preceded by a `/* subset *\/` comment naming its coverage. */
const blocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/gi)];
if (!blocks.length) throw new Error("no @font-face blocks parsed — did the CSS format change?");

const out = [];
let kept = 0;
for (const [, subset, block] of blocks) {
  if (!KEEP_SUBSETS.has(subset)) continue;
  const family = /font-family:\s*'([^']+)'/.exec(block)?.[1] ?? "font";
  const weight = /font-weight:\s*(\d+)/.exec(block)?.[1] ?? "400";
  const style = /font-style:\s*(\w+)/.exec(block)?.[1] ?? "normal";
  const url = /url\((https:[^)]+)\)/.exec(block)?.[1];
  if (!url) continue;

  const name = `${family.toLowerCase().replace(/\s+/g, "-")}-${weight}-${style}-${subset}.woff2`;
  const bytes = new Uint8Array(await (await fetch(url)).arrayBuffer());
  await writeFile(join(outDir, name), bytes);
  kept += 1;

  out.push(
    block
      .replace(/url\(https:[^)]+\)/, `url("/fonts/${name}")`)
      .replace(/^@font-face/, `/* ${subset} */\n@font-face`),
  );
  console.log(`  ${name}  ${(bytes.length / 1024).toFixed(0)} KB`);
}

const sheet = `/*
  Self-hosted webfonts. Generated by scripts/fetch-fonts.mjs — do not hand-edit.

  Served from this origin so that reading the paper does not tell a third party
  who is reading it. Regenerate by running the script, not by editing here.
*/
${out.join("\n\n")}
`;
await writeFile(join(root, "src", "fonts.css"), sheet);
console.log(`\nwrote ${kept} font files and src/fonts.css`);
