/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TownReporterDotzipRouteImport } from './routes/TownReporter[.]zip'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CorrectionsRouteImport } from './routes/corrections'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as GetTheCodeRouteImport } from './routes/get-the-code'
import { Route as HowWeReportRouteImport } from './routes/how-we-report'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as DeskIndexRouteImport } from './routes/desk.index'
import { Route as DeskDarkRouteImport } from './routes/desk.dark'
import { Route as DeskMemoryRouteImport } from './routes/desk.memory'
import { Route as DeskPublishedRouteImport } from './routes/desk.published'
import { Route as DeskQueueRouteImport } from './routes/desk.queue'
import { Route as DeskScanRouteImport } from './routes/desk.scan'
import { Route as DeskSourcesRouteImport } from './routes/desk.sources'
import { Route as EvidenceVersionIdRouteImport } from './routes/evidence.$versionId'
import { Route as EvidenceCompareRouteImport } from './routes/evidence.compare'
import { Route as NewsletterConfirmRouteImport } from './routes/newsletter.confirm'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronMonitorsRouteImport } from './routes/api/cron.monitors'
import { Route as DeskStoryLeadIdRouteImport } from './routes/desk.story.$leadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TownReporterDotzipRoute = TownReporterDotzipRouteImport.update({
  id: '/TownReporter.zip',
  path: '/TownReporter.zip',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectionsRoute = CorrectionsRouteImport.update({
  id: '/corrections',
  path: '/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const GetTheCodeRoute = GetTheCodeRouteImport.update({
  id: '/get-the-code',
  path: '/get-the-code',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeReportRoute = HowWeReportRouteImport.update({
  id: '/how-we-report',
  path: '/how-we-report',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskDarkRoute = DeskDarkRouteImport.update({
  id: '/dark',
  path: '/dark',
  getParentRoute: () => DeskRoute,
} as any)
const DeskMemoryRoute = DeskMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => DeskRoute,
} as any)
const DeskPublishedRoute = DeskPublishedRouteImport.update({
  id: '/published',
  path: '/published',
  getParentRoute: () => DeskRoute,
} as any)
const DeskQueueRoute = DeskQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => DeskRoute,
} as any)
const DeskScanRoute = DeskScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => DeskRoute,
} as any)
const DeskSourcesRoute = DeskSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => DeskRoute,
} as any)
const EvidenceVersionIdRoute = EvidenceVersionIdRouteImport.update({
  id: '/evidence/$versionId',
  path: '/evidence/$versionId',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceCompareRoute = EvidenceCompareRouteImport.update({
  id: '/evidence/compare',
  path: '/evidence/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterConfirmRoute = NewsletterConfirmRouteImport.update({
  id: '/newsletter/confirm',
  path: '/newsletter/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronMonitorsRoute = ApiCronMonitorsRouteImport.update({
  id: '/api/cron/monitors',
  path: '/api/cron/monitors',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskStoryLeadIdRoute = DeskStoryLeadIdRouteImport.update({
  id: '/story/$leadId',
  path: '/story/$leadId',
  getParentRoute: () => DeskRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/TownReporter.zip': typeof TownReporterDotzipRoute
  '/about': typeof AboutRoute
  '/corrections': typeof CorrectionsRoute
  '/desk': typeof DeskRouteWithChildren
  '/feed': typeof FeedRoute
  '/get-the-code': typeof GetTheCodeRoute
  '/how-we-report': typeof HowWeReportRoute
  '/login': typeof LoginRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/desk/dark': typeof DeskDarkRoute
  '/desk/memory': typeof DeskMemoryRoute
  '/desk/published': typeof DeskPublishedRoute
  '/desk/queue': typeof DeskQueueRoute
  '/desk/scan': typeof DeskScanRoute
  '/desk/sources': typeof DeskSourcesRoute
  '/evidence/$versionId': typeof EvidenceVersionIdRoute
  '/evidence/compare': typeof EvidenceCompareRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/desk/': typeof DeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/monitors': typeof ApiCronMonitorsRoute
  '/desk/story/$leadId': typeof DeskStoryLeadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/TownReporter.zip': typeof TownReporterDotzipRoute
  '/about': typeof AboutRoute
  '/corrections': typeof CorrectionsRoute
  '/feed': typeof FeedRoute
  '/get-the-code': typeof GetTheCodeRoute
  '/how-we-report': typeof HowWeReportRoute
  '/login': typeof LoginRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/desk/dark': typeof DeskDarkRoute
  '/desk/memory': typeof DeskMemoryRoute
  '/desk/published': typeof DeskPublishedRoute
  '/desk/queue': typeof DeskQueueRoute
  '/desk/scan': typeof DeskScanRoute
  '/desk/sources': typeof DeskSourcesRoute
  '/evidence/$versionId': typeof EvidenceVersionIdRoute
  '/evidence/compare': typeof EvidenceCompareRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/desk': typeof DeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/monitors': typeof ApiCronMonitorsRoute
  '/desk/story/$leadId': typeof DeskStoryLeadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/TownReporter.zip': typeof TownReporterDotzipRoute
  '/about': typeof AboutRoute
  '/corrections': typeof CorrectionsRoute
  '/desk': typeof DeskRouteWithChildren
  '/feed': typeof FeedRoute
  '/get-the-code': typeof GetTheCodeRoute
  '/how-we-report': typeof HowWeReportRoute
  '/login': typeof LoginRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/desk/dark': typeof DeskDarkRoute
  '/desk/memory': typeof DeskMemoryRoute
  '/desk/published': typeof DeskPublishedRoute
  '/desk/queue': typeof DeskQueueRoute
  '/desk/scan': typeof DeskScanRoute
  '/desk/sources': typeof DeskSourcesRoute
  '/evidence/$versionId': typeof EvidenceVersionIdRoute
  '/evidence/compare': typeof EvidenceCompareRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/desk/': typeof DeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/monitors': typeof ApiCronMonitorsRoute
  '/desk/story/$leadId': typeof DeskStoryLeadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/TownReporter.zip'
    | '/about'
    | '/corrections'
    | '/desk'
    | '/feed'
    | '/get-the-code'
    | '/how-we-report'
    | '/login'
    | '/articles/$slug'
    | '/desk/dark'
    | '/desk/memory'
    | '/desk/published'
    | '/desk/queue'
    | '/desk/scan'
    | '/desk/sources'
    | '/evidence/$versionId'
    | '/evidence/compare'
    | '/newsletter/confirm'
    | '/desk/'
    | '/api/auth/$'
    | '/api/cron/monitors'
    | '/desk/story/$leadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/TownReporter.zip'
    | '/about'
    | '/corrections'
    | '/feed'
    | '/get-the-code'
    | '/how-we-report'
    | '/login'
    | '/articles/$slug'
    | '/desk/dark'
    | '/desk/memory'
    | '/desk/published'
    | '/desk/queue'
    | '/desk/scan'
    | '/desk/sources'
    | '/evidence/$versionId'
    | '/evidence/compare'
    | '/newsletter/confirm'
    | '/desk'
    | '/api/auth/$'
    | '/api/cron/monitors'
    | '/desk/story/$leadId'
  id:
    | '__root__'
    | '/'
    | '/TownReporter.zip'
    | '/about'
    | '/corrections'
    | '/desk'
    | '/feed'
    | '/get-the-code'
    | '/how-we-report'
    | '/login'
    | '/articles/$slug'
    | '/desk/dark'
    | '/desk/memory'
    | '/desk/published'
    | '/desk/queue'
    | '/desk/scan'
    | '/desk/sources'
    | '/evidence/$versionId'
    | '/evidence/compare'
    | '/newsletter/confirm'
    | '/desk/'
    | '/api/auth/$'
    | '/api/cron/monitors'
    | '/desk/story/$leadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TownReporterDotzipRoute: typeof TownReporterDotzipRoute
  AboutRoute: typeof AboutRoute
  CorrectionsRoute: typeof CorrectionsRoute
  DeskRoute: typeof DeskRouteWithChildren
  FeedRoute: typeof FeedRoute
  GetTheCodeRoute: typeof GetTheCodeRoute
  HowWeReportRoute: typeof HowWeReportRoute
  LoginRoute: typeof LoginRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  EvidenceVersionIdRoute: typeof EvidenceVersionIdRoute
  EvidenceCompareRoute: typeof EvidenceCompareRoute
  NewsletterConfirmRoute: typeof NewsletterConfirmRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronMonitorsRoute: typeof ApiCronMonitorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/TownReporter.zip': {
      id: '/TownReporter.zip'
      path: '/TownReporter.zip'
      fullPath: '/TownReporter.zip'
      preLoaderRoute: typeof TownReporterDotzipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrections': {
      id: '/corrections'
      path: '/corrections'
      fullPath: '/corrections'
      preLoaderRoute: typeof CorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-the-code': {
      id: '/get-the-code'
      path: '/get-the-code'
      fullPath: '/get-the-code'
      preLoaderRoute: typeof GetTheCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-report': {
      id: '/how-we-report'
      path: '/how-we-report'
      fullPath: '/how-we-report'
      preLoaderRoute: typeof HowWeReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/dark': {
      id: '/desk/dark'
      path: '/dark'
      fullPath: '/desk/dark'
      preLoaderRoute: typeof DeskDarkRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/memory': {
      id: '/desk/memory'
      path: '/memory'
      fullPath: '/desk/memory'
      preLoaderRoute: typeof DeskMemoryRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/published': {
      id: '/desk/published'
      path: '/published'
      fullPath: '/desk/published'
      preLoaderRoute: typeof DeskPublishedRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/queue': {
      id: '/desk/queue'
      path: '/queue'
      fullPath: '/desk/queue'
      preLoaderRoute: typeof DeskQueueRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/scan': {
      id: '/desk/scan'
      path: '/scan'
      fullPath: '/desk/scan'
      preLoaderRoute: typeof DeskScanRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/sources': {
      id: '/desk/sources'
      path: '/sources'
      fullPath: '/desk/sources'
      preLoaderRoute: typeof DeskSourcesRouteImport
      parentRoute: typeof DeskRoute
    }
    '/evidence/$versionId': {
      id: '/evidence/$versionId'
      path: '/evidence/$versionId'
      fullPath: '/evidence/$versionId'
      preLoaderRoute: typeof EvidenceVersionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/compare': {
      id: '/evidence/compare'
      path: '/evidence/compare'
      fullPath: '/evidence/compare'
      preLoaderRoute: typeof EvidenceCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/confirm': {
      id: '/newsletter/confirm'
      path: '/newsletter/confirm'
      fullPath: '/newsletter/confirm'
      preLoaderRoute: typeof NewsletterConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/monitors': {
      id: '/api/cron/monitors'
      path: '/api/cron/monitors'
      fullPath: '/api/cron/monitors'
      preLoaderRoute: typeof ApiCronMonitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/story/$leadId': {
      id: '/desk/story/$leadId'
      path: '/story/$leadId'
      fullPath: '/desk/story/$leadId'
      preLoaderRoute: typeof DeskStoryLeadIdRouteImport
      parentRoute: typeof DeskRoute
    }
  }
}

interface DeskRouteChildren {
  DeskDarkRoute: typeof DeskDarkRoute
  DeskMemoryRoute: typeof DeskMemoryRoute
  DeskPublishedRoute: typeof DeskPublishedRoute
  DeskQueueRoute: typeof DeskQueueRoute
  DeskScanRoute: typeof DeskScanRoute
  DeskSourcesRoute: typeof DeskSourcesRoute
  DeskIndexRoute: typeof DeskIndexRoute
  DeskStoryLeadIdRoute: typeof DeskStoryLeadIdRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskDarkRoute: DeskDarkRoute,
  DeskMemoryRoute: DeskMemoryRoute,
  DeskPublishedRoute: DeskPublishedRoute,
  DeskQueueRoute: DeskQueueRoute,
  DeskScanRoute: DeskScanRoute,
  DeskSourcesRoute: DeskSourcesRoute,
  DeskIndexRoute: DeskIndexRoute,
  DeskStoryLeadIdRoute: DeskStoryLeadIdRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TownReporterDotzipRoute: TownReporterDotzipRoute,
  AboutRoute: AboutRoute,
  CorrectionsRoute: CorrectionsRoute,
  DeskRoute: DeskRouteWithChildren,
  FeedRoute: FeedRoute,
  GetTheCodeRoute: GetTheCodeRoute,
  HowWeReportRoute: HowWeReportRoute,
  LoginRoute: LoginRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  EvidenceVersionIdRoute: EvidenceVersionIdRoute,
  EvidenceCompareRoute: EvidenceCompareRoute,
  NewsletterConfirmRoute: NewsletterConfirmRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronMonitorsRoute: ApiCronMonitorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
